# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "ThreeT.xcodeproj")
    build_app(scheme: "ThreeT")
    #upload_to_testflight
  end
end

lane :screenshots do
  capture_screenshots(
    dark_mode: false,
    output_directory: "./fastlane/screenshots/light"
  )
  
  capture_screenshots(
    dark_mode: true,
    output_directory: "./fastlane/screenshots/dark"
  )
end

